permalink: pretty
author: Your Name Here
email: example@example.com
url: https://example.com
description:
  - An example Jekyll blog using Poole. Replace this text with a description of your site.
repo: https://github.com/citrusui/poole
sass:
  style: :compressed
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-sitemap
title: Poole Example
paginate: 1
paginate_path: "/page/:num/"
